version: "3.9"

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8085:80"
    volumes:
      - .:/app
    environment:
      - APP_ENV=production
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=gestion_immobilier
      - DB_USERNAME=root
      - DB_PASSWORD=root_password_here

  database:
    image: mysql:${MYSQL_VERSION:-8.0}
    environment:
      MYSQL_DATABASE: gestion_immobilier
      MYSQL_ROOT_PASSWORD: root_password_here
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8087:80"
    environment:
      PMA_HOST: database
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root_password_here

volumes:
  db-data:
